name: Clay Pigeon Winery
favicon: null
layout_spectrum: 0.37064181361347437
typography_spectrum: 0.7643846715800464
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5054022716358304
  lightness: 0.4167663031257689
  saturation: 0.6568035245873034
  rhythmicContrast: 0.8101149518042803
purpose: []
