name: Clay Pigeon Winery
favicon: null
layout_spectrum: 0.50983
typography_spectrum: 0.79186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1b1b'
    - '#ff2033'
    - '#d4d4d4'
    - '#858585'
  brandStrength: 0.5054022716358304
  lightness: 0.4167663031257689
  saturation: 0.6568035245873034
  rhythmicContrast: 0.8101149518042803
purpose: []
